---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/register":
    post:
      summary: Creates a new user account
      tags:
      - Registration
      security: []
      parameters: []
      responses:
        '200':
          description: user registered successfully
        '422':
          description: invalid request
        '500':
          description: internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: user@example.com
                    password:
                      type: string
                      example: password123
                    password_confirmation:
                      type: string
                      example: password123
                  required:
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/sessions":
    post:
      summary: Creates a session
      tags:
      - Sessions
      security: []
      parameters: []
      responses:
        '200':
          description: session created
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
    get:
      summary: Lists all active sessions
      tags:
      - Sessions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: sessions found
        '401':
          description: unauthorized
    delete:
      summary: Revokes all other sessions
      tags:
      - Sessions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: sessions revoked
  "/api/v1/session":
    delete:
      summary: Logs out current session
      tags:
      - Sessions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: logged out successfully
  "/api/v1/refresh_token":
    post:
      summary: Refreshes current session token
      tags:
      - Sessions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: token refreshed
        '401':
          description: invalid session
  "/api/v1/usernames/verify":
    get:
      summary: Verifies username availability
      tags:
      - Usernames
      security:
      - bearer_auth: []
      parameters:
      - name: username
        in: query
        required: true
        description: Username to verify
        schema:
          type: string
      responses:
        '200':
          description: username availability checked
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                    - success
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          available:
                            type: boolean
                          username:
                            type: string
                        required:
                        - available
                        - username
                    required:
                    - id
                    - type
                    - attributes
                  meta:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      message:
                        type: string
                    required:
                    - timestamp
                    - message
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                    - error
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                      - code
                      - detail
                  meta:
                    type: object
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                    required:
                    - timestamp
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearer_format: JWT
security:
- bearer_auth: []
